behaviors:
  AgentSphereBehavior: # This name MUST match the "Behavior Name" in the Agent's Behavior Parameters component in Unity
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple # Use 'simple' if not using visual observations from a camera
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 300000 # Let's run for a small number of steps for this test
    time_horizon: 64
    summary_freq: 10000